# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"coin_model": "50_core.ipynb",
         "ja": "50_core.ipynb",
         "phi_set": "50_core.ipynb",
         "observation_single_1": "50_core.ipynb",
         "observation_single_0": "50_core.ipynb",
         "observation_small_set_0": "50_core.ipynb",
         "observation_small_set_balanced": "50_core.ipynb",
         "observation_small_set_1": "50_core.ipynb",
         "observation_large_set_neutral": "50_core.ipynb",
         "observation_large_set_biased": "50_core.ipynb",
         "prior_belief_set_fair": "50_core.ipynb",
         "prior_belief_set_bias_0": "50_core.ipynb",
         "prior_belief_set_bias_1": "50_core.ipynb",
         "prior_belief_set_uninformative": "50_core.ipynb",
         "likelihood_vector_fn": "50_core.ipynb",
         "likelihood_observation_set_fn": "50_core.ipynb",
         "marginal_fn": "50_core.ipynb",
         "BayesianBeliefUpdate_singlePhi": "50_core.ipynb",
         "BayesianBeliefUpdate": "50_core.ipynb",
         "BayesianBeliefUpdateReport": "50_core.ipynb"}

modules = ["core.py"]

doc_url = "https://jerzydziewierz.github.io/bayesian_reasoning_v0/"

git_url = "https://github.com/jerzydziewierz/bayesian_reasoning_v0/tree/master/"

def custom_doc_links(name): return None
